### ISSUE TITLE
Options to include object public Fields, Properties, Methods and Values that don't include XML Comments

### ISSUE THREAD

**Issue by recrutch** [clcrutch/DotNetMDDocs#15]
When a public Property (Field, Method or Value) does not include a XML Comment, they don't appear in the documentation.  It would be nice if the Documentation would include them through an option.

**Comment by clcrutch** [comment]
I ended up updating DotNetMDDocs to always produce markdown files for a type/member, even if there are no XML docs.  I feel that this is more in line with other documentation generators.
