### ISSUE TITLE
xml tags in API doc comments are dropped from markdown

### ISSUE THREAD

**Issue by AArnott** [clcrutch/DotNetMDDocs#9]
As can be seen in https://github.com/AArnott/Nerdbank.GitVersioning/wiki/AssemblyFileVersion

![image](https://user-images.githubusercontent.com/3548/44354834-bdebdd80-a45f-11e8-988a-4c0832814ecf.png)

There is clearly a missing word in the sentence there. The original xml doc comment was:

```cs
/// <summary>
/// Gets the version string to use for the <see cref="System.Reflection.AssemblyFileVersionAttribute"/>.
/// </summary>
public Version AssemblyFileVersion => this.Version;
```

**Comment by clcrutch** [comment]
This is fixed for the "see" tag in the current version.
